version: '3.8'
services:
  dev_db:
    platform: linux/x86_64
    image: postgres:14.5
    volumes:
      - dev_db_vol:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - db_network
    # hostname: dev_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']

  customer_api:
    image: customer-api:${CUSTOMER_API_IMAGE_NAME}
    ports:
      - '${PORT}:80'
    networks:
      - db_network
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dev_db:5432/${POSTGRES_DB}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
      - EMAIL_NAME=${EMAIL_NAME}
      - EMAIL_FROM=${EMAIL_FROM}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_INITIAL_PASSWORD=${ADMIN_INITIAL_PASSWORD}
      - BUCKET_NAME=${BUCKET_NAME}
    depends_on:
      - dev_db
    links:
      - dev_db
    restart: always
    # command:
    #   - sh
    #   - -c
    #   - >
    #     wait-for-it.sh dev_db:5432 &&
    #     run_prisma_with_retries.sh generate &&
    #     run_prisma_with_retries.sh migrate deploy &&
    #     node dist/apps/customer-api/main.js

volumes:
  dev_db_vol:
networks:
  db_network:
    driver: bridge
