import { registerEnumType } from '@nestjs/graphql';

export enum EmailType {
  VERIFICATION = 'VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  ADMIN_REGISTRATION = 'ADMIN_REGISTRATION',
  WELCOME = 'WELCOME',
  UNRESOLVED_UNDERPAID = 'UNRESOLVED_UNDERPAID',
  ADMIN_UNRESOLVED_DELAYED = 'ADMIN_UNRESOLVED_DELAYED',
  ADMIN_UNRESOLVED_MULTIPLE = 'ADMIN_UNRESOLVED_MULTIPLE',
  ADMIN_UNRESOLVED_OVERPAID = 'ADMIN_UNRESOLVED_OVERPAID',
  ADMIN_UNRESOLVED_UNDERPAID = 'ADMIN_UNRESOLVED_UNDERPAID',
  ADMIN_UNRESOLVED_OTHER = 'ADMIN_UNRESOLVED_OTHER',
  PURCHASE_CONFIRMATION = 'PURCHASE_CONFIRMATION',
  REFERRER_COMMISSION = 'REFERRER_COMMISSION',
}

registerEnumType(EmailType, { name: 'EmailType' });
